config/routes.rb
Homesite::Application.routes.draw do
  
  resources :volunteers

  resources :educations

  get "home/index"

  resources :projects

  resources :users

  resources :user_sessions

  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  resources :employments

  
  root :to => 'home#index'

end

app/models/volunteer.rb
class Volunteer < ActiveRecord::Base
  def from_to_str
    "#{self.from.strftime("%Y %b")} - "+((self.current)?((I18n.locale.to_s == 'no')?"Naa":"Now"):"#{self.to.strftime("%Y %b")}")
  end
end

app/controllers/volunteers_controller.rb
class VolunteersController < ApplicationController
  before_filter :require_user, :only => [:new, :create, :edit, :update, :destroy]

  # GET /volunteers
  # GET /volunteers.json
  def index
    @volunteers = Volunteer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @volunteers }
    end
  end

  # GET /volunteers/1
  # GET /volunteers/1.json
  def show
    @volunteer = Volunteer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @volunteer }
    end
  end

  # GET /volunteers/new
  # GET /volunteers/new.json
  def new
    @volunteer = Volunteer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @volunteer }
    end
  end

  # GET /volunteers/1/edit
  def edit
    @volunteer = Volunteer.find(params[:id])
  end

  # POST /volunteers
  # POST /volunteers.json
  def create
    @volunteer = Volunteer.new(params[:volunteer])

    respond_to do |format|
      if @volunteer.save
        format.html { redirect_to @volunteer, notice: 'Volunteer was successfully created.' }
        format.json { render json: @volunteer, status: :created, location: @volunteer }
      else
        format.html { render action: "new" }
        format.json { render json: @volunteer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /volunteers/1
  # PUT /volunteers/1.json
  def update
    @volunteer = Volunteer.find(params[:id])

    respond_to do |format|
      if @volunteer.update_attributes(params[:volunteer])
        format.html { redirect_to @volunteer, notice: 'Volunteer was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @volunteer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /volunteers/1
  # DELETE /volunteers/1.json
  def destroy
    @volunteer = Volunteer.find(params[:id])
    @volunteer.destroy

    respond_to do |format|
      format.html { redirect_to volunteers_url }
      format.json { head :ok }
    end
  end
end

app/helpers/volunteers_helper.rb
module VolunteersHelper
end

app/views/volunteers/_form.html.erb
<%= form_for(@volunteer) do |f| %>
  <% if @volunteer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@volunteer.errors.count, "error") %> prohibited this volunteer from being saved:</h2>

      <ul>
      <% @volunteer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title_en %><br />
    <%= f.text_field :title_en %>
  </div>
  <div class="field">
    <%= f.label :title_no %><br />
    <%= f.text_field :title_no %>
  </div>
  <div class="field">
    <%= f.label :from %><br />
    <%= f.datetime_select :from %>
  </div>
  <div class="field">
    <%= f.label :to %><br />
    <%= f.datetime_select :to %>
  </div>
  <div class="field">
    <%= f.label :current %><br />
    <%= f.check_box :current %>
  </div>
  <div class="field">
    <%= f.label :description_no %><br />
    <%= f.text_area :description_no %>
  </div>
  <div class="field">
    <%= f.label :description_en %><br />
    <%= f.text_area :description_en %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/volunteers/edit.html.erb
<h1>Editing volunteer</h1>

<%= render 'form' %>

<%= link_to 'Show', @volunteer %> |
<%= link_to 'Back', volunteers_path %>

app/views/volunteers/index.html.erb
<% title (I18n.locale.to_s == 'no')?"Frivillig":"Voulenteer" %>

<table>
  <% for v in @volunteers %>
    <tr>
      <td>
      <h4><%= (I18n.locale.to_s == 'no')?"#{v.title_no}":"#{v.title_en}" %></h4><br />
      <%= v.from_to_str %><br />
      <p><i><%= (I18n.locale.to_s == 'no')?"#{v.description_no}":"#{v.description_en}"%></i></p>
      <%= link_to "Show", v %>
      <% if current_user %>
      <%= link_to "Edit", edit_volunteer_path(v) %>
      <%= link_to "Destroy", v, :confirm => 'Are you sure?', :method => :delete %>
      <%end%>
      </td>
    </tr>
  <% end %>
</table>

<br />
<% if current_user %>
  <%= link_to "New Voulenteer", new_volunteer_path %>
<% end %>

app/views/volunteers/new.html.erb
<h1>New volunteer</h1>

<%= render 'form' %>

<%= link_to 'Back', volunteers_path %>

app/views/volunteers/show.html.erb
<% title (I18n.locale.to_s == 'no')?"Frivillig":"Volunteer" %>

<p>
  <h4><%= (I18n.locale.to_s == 'no')?"#{@volunteer.title_no}":"#{@volunteer.title_en}" %></h4>
</p>
<p>
  <%= @volunteer.from_to_str %>
</p>
<p>
  <%= (I18n.locale.to_s == 'no')?"#{@volunteer.description_no}":"#{@volunteer.description_en}" %>
</p>
<p>
<% if current_user %>
  <%= link_to "Edit", edit_volunteer_path(@voulenteer) %>
  <%= link_to "Destroy", @volunteer, :confirm => 'Are you sure?', :method => :delete %>
<%end%>
  <%= link_to "View All", volunteers_path %>
</p>