config/routes.rb
Homesite::Application.routes.draw do
  
  resources :volunteers

  resources :educations

  get "home/index"

  resources :projects

  resources :users

  resources :user_sessions

  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  resources :employments

  
  root :to => 'home#index'

end

app/models/employment.rb
class Employment < ActiveRecord::Base
  def from_to_str
    "#{self.from.strftime("%Y %b")} - "+((self.current)?((I18n.locale.to_s == 'no')?"Naa":"Now"):"#{self.to.strftime("%Y %b")}")
  end
end

app/controllers/employments_controller.rb
class EmploymentsController < ApplicationController
  before_filter :require_user, :only => [:new, :create, :edit, :update, :destroy]

  def index
    @employments = Employment.order("current DESC, employments.to DESC")
  end

  def show
    @employment = Employment.find(params[:id])
  end

  def new
    @employment = Employment.new
  end

  def create
    @employment = Employment.new(params[:employment])
    if @employment.save
      redirect_to @employment, :notice => "Successfully created employment."
    else
      render :action => 'new'
    end
  end

  def edit
    @employment = Employment.find(params[:id])
  end

  def update
    @employment = Employment.find(params[:id])
    if @employment.update_attributes(params[:employment])
      redirect_to @employment, :notice  => "Successfully updated employment."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @employment = Employment.find(params[:id])
    @employment.destroy
    redirect_to employments_url, :notice => "Successfully destroyed employment."
  end
end

app/helpers/employments_helper.rb
module EmploymentsHelper
end

app/views/employments/_form.html.erb
<%= form_for @employment do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :company %><br />
    <%= f.text_field :company %>
  </p>
  <p>
    <%= f.label :from %><br />
    <%= f.datetime_select :from %>
  </p>
  <p>
    <%= f.label :to %><br />
    <%= f.datetime_select :to %>
  </p>
  <p>
    <%= f.label :current %><br />
    <%= f.check_box :current %>
  </p>
  <p>
    <%= f.label :title_no %><br />
    <%= f.text_field :title_no %>
  </p>
  <p>
    <%= f.label :title_en %><br />
    <%= f.text_field :title_en %>
  </p>
  <p>
    <%= f.label :description_no %><br />
    <%= f.text_area :description_no %>
  </p>
  <p>
    <%= f.label :description_en %><br />
    <%= f.text_area :description_en %>
  </p>

  <p><%= f.submit %></p>
<% end %>

app/views/employments/edit.html.erb
<% title "Edit Employment" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @employment %> |
  <%= link_to "View All", employments_path %>
</p>

app/views/employments/index.html.erb
<% title (I18n.locale.to_s == 'no')?"Jobb":"Employments" %>

<table>
  <% for employment in @employments %>
    <tr>
      <td>
      <h4><%= employment.company %></h4><br />
      <%= (I18n.locale.to_s == 'no')?"#{employment.title_no}":"#{employment.title_en}" %><br />
      <%= employment.from_to_str %><br />
      <p><i><%= (I18n.locale.to_s == 'no')?"#{employment.description_no}":"#{employment.description_en}"%></i></p>
      <%= link_to "Show", employment %>
      <% if current_user %>
      <%= link_to "Edit", edit_employment_path(employment) %>
      <%= link_to "Destroy", employment, :confirm => 'Are you sure?', :method => :delete %>
      <%end%>
      </td>
    </tr>
  <% end %>
</table>

<br />
<% if current_user %>
  <%= link_to "New Employment", new_employment_path %>
<% end %>

app/views/employments/new.html.erb
<% title "New Employment" %>

<%= render 'form' %>

<p><%= link_to "Back to List", employments_path %></p>

app/views/employments/show.html.erb
<% title (I18n.locale.to_s == 'no')?"Jobb":"Employment" %>

<p>
  <h4><%= @employment.company %></h4>
</p>
<p>
  <%= (I18n.locale.to_s == 'no')?"#{@employment.title_no}":"#{@employment.title_en}" %>
</p>
<p>
  <%= @employment.from_to_str %>
</p>
<p>
  <%= (I18n.locale.to_s == 'no')?"#{@employment.description_no}":"#{@employment.description_en}" %>
</p>
<p>
<% if current_user %>
  <%= link_to "Edit", edit_employment_path(@employment) %>
  <%= link_to "Destroy", @employment, :confirm => 'Are you sure?', :method => :delete %>
<%end%>
  <%= link_to "View All", employments_path %>
</p>