config/routes.rb
Homesite::Application.routes.draw do
  
  resources :volunteers

  resources :educations

  get "home/index"

  resources :projects

  resources :users

  resources :user_sessions

  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  resources :employments

  
  root :to => 'home#index'

end

app/models/education.rb
class Education < ActiveRecord::Base
  def from_to_str
    "#{self.from.strftime("%Y %b")} - "+((self.current)?((I18n.locale.to_s == 'no')?"Naa":"Now"):"#{self.to.strftime("%Y %b")}")
  end

end

app/controllers/educations_controller.rb
class EducationsController < ApplicationController
before_filter :require_user, :only => [:new, :create, :edit, :update, :destroy]

  # GET /educations
  # GET /educations.json
  def index
    @educations = Education.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @educations }
    end
  end

  # GET /educations/1
  # GET /educations/1.json
  def show
    @education = Education.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @education }
    end
  end

  # GET /educations/new
  # GET /educations/new.json
  def new
    @education = Education.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @education }
    end
  end

  # GET /educations/1/edit
  def edit
    @education = Education.find(params[:id])
  end

  # POST /educations
  # POST /educations.json
  def create
    @education = Education.new(params[:education])

    respond_to do |format|
      if @education.save
        format.html { redirect_to @education, notice: 'Education was successfully created.' }
        format.json { render json: @education, status: :created, location: @education }
      else
        format.html { render action: "new" }
        format.json { render json: @education.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /educations/1
  # PUT /educations/1.json
  def update
    @education = Education.find(params[:id])

    respond_to do |format|
      if @education.update_attributes(params[:education])
        format.html { redirect_to @education, notice: 'Education was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @education.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /educations/1
  # DELETE /educations/1.json
  def destroy
    @education = Education.find(params[:id])
    @education.destroy

    respond_to do |format|
      format.html { redirect_to educations_url }
      format.json { head :ok }
    end
  end
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/views/educations/_form.html.erb
<%= form_for(@education) do |f| %>
  <% if @education.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@education.errors.count, "error") %> prohibited this education from being saved:</h2>

      <ul>
      <% @education.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title_en %><br />
    <%= f.text_field :title_en %>
  </div>
  <div class="field">
    <%= f.label :title_no %><br />
    <%= f.text_field :title_no %>
  </div>
  <div class="field">
    <%= f.label :from %><br />
    <%= f.datetime_select :from %>
  </div>
  <div class="field">
    <%= f.label :to %><br />
    <%= f.datetime_select :to %>
  </div>
  <div class="field">
    <%= f.label :current %><br />
    <%= f.check_box :current %>
  </div>
  <div class="field">
    <%= f.label :description_no %><br />
    <%= f.text_area :description_no %>
  </div>
  <div class="field">
    <%= f.label :description_en %><br />
    <%= f.text_area :description_en %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/educations/edit.html.erb
<h1>Editing education</h1>

<%= render 'form' %>

<%= link_to 'Show', @education %> |
<%= link_to 'Back', educations_path %>

app/views/educations/index.html.erb
<% title (I18n.locale.to_s == 'no')?"Utdanning":"Education" %>
<table>

<% @educations.each do |education| %>
<tr>
  <td>
    <h4><%= (I18n.locale.to_s == 'no')?"#{education.title_no}":"#{education.title_en}" %></h4><br />
    <%= education.from_to_str %><br />
    <p><i><%= (I18n.locale.to_s == 'no')?"#{education.description_no}":"#{education.description_en}" %></i></p><br />
    <%= link_to 'Show', education %>
    <%if current_user %>
    <%= link_to 'Edit', edit_education_path(education) %>
    <%= link_to 'Destroy', education, confirm: 'Are you sure?', method: :delete %>
    <%end%>
    </td>
  </tr>
<% end %>
</table>

<br />
<%if current_user %>
<%= link_to 'New Education', new_education_path %>
<%end%>

app/views/educations/new.html.erb
<h1>New education</h1>

<%= render 'form' %>

<%= link_to 'Back', educations_path %>

app/views/educations/show.html.erb
<% title (I18n.locale.to_s == 'no')?"Utdanning":"Education" %>

<p>
 <h4><%= (I18n.locale.to_s == 'no')?"#{@education.title_no}":"#{@education.title_en}" %></h4>
</p>
<p>
  <%= @education.from_to_str %>
</p>
<p>
  <%= (I18n.locale.to_s == 'no')?"#{@education.description_no}":"#{@education.description_en}" %>
</p>
<p>
<% if current_user %>
  <%= link_to "Edit", edit_education_path(@education) %>
  <%= link_to "Destroy", @education, :confirm => 'Are you sure?', :method => :delete %>
<%end%>
  <%= link_to "View All", educations_path %>
</p>